-- ⚠️ RETIRED. DO NOT RUN THIS. USE  node scripts/demo-account.mjs --run  INSTEAD.
--
-- This file was correct, careful, well commented, and NEVER ONCE EXECUTED.
--
-- Why: it contained this line.
--
--     demo_id uuid := '00000000-0000-4000-8000-000000000001'; -- <-- REPLACE with the real auth uuid
--
-- To use it you had to create an auth user in the Supabase dashboard, copy its uuid, paste it in
-- here, and then run the file. Four steps, four chances to stop, and we stopped at the first one.
-- It sat in the repo looking finished.
--
-- A HUMAN STEP IS A STEP THAT GETS SKIPPED. The khoji_writer password rotation taught us the same
-- lesson on 13 July and it cost an afternoon: the moment a human has to carry a value from one
-- system into another, either automate it or expect to find it undone.
--
-- scripts/demo-account.mjs creates the auth user, the profile, the ACTIVE subscription and the
-- demo data in one command, and it is idempotent. Nothing is copied by hand, so there is nothing
-- left to forget.
--
-- The one thing still done by hand, because there is no API for it: add the fixed test OTP in
-- Supabase -> Authentication -> Sign In / Providers -> Phone -> Test OTP:
--
--     +447700900123  =>  123456
--
-- The script prints that reminder, and the exact text to paste into App Store Connect, every run.
