// Trade specific landing page content. One entry per trade, used to generate a
// static page at /for/<slug>. Pure data, no AI, no network. The claims lists are
// general allowable expenses for that trade, in plain English.

export interface Trade {
  slug: string;
  name: string; // singular, capitalised, e.g. Electrician
  plural: string; // lowercase plural, e.g. electricians
  emoji: string;
  blurb: string; // hero sub line
  claims: string[]; // common allowable costs for this trade
  cis: boolean; // construction trade, CIS relevant
}

export const TRADES: Trade[] = [
  {
    slug: 'electricians',
    name: 'Electrician',
    plural: 'electricians',
    emoji: '⚡',
    blurb: 'Snap a receipt at the wholesaler, log a job from the van, and let Lekhio keep you ready for tax. All on WhatsApp.',
    claims: ['Cable, fittings and consumables', 'Test equipment and tools', 'Van running costs or 55p a mile', 'NICEIC or NAPIT registration', 'Part P and test certification', 'Public liability insurance'],
    cis: true,
  },
  {
    slug: 'plumbers',
    name: 'Plumber',
    plural: 'plumbers',
    emoji: '🔧',
    blurb: 'Photograph the merchant receipt, log the boiler job, and your books are done as you work. No laptop, no spreadsheets.',
    claims: ['Pipe, fittings and parts', 'Tools and test kit', 'Van costs or simplified mileage', 'Gas Safe registration', 'Public liability insurance', 'Workwear and protective gear'],
    cis: true,
  },
  {
    slug: 'builders',
    name: 'Builder',
    plural: 'builders',
    emoji: '🧱',
    blurb: 'Materials, labour, subbies and CIS, all logged from a text. Lekhio keeps the lot straight and tax ready.',
    claims: ['Materials, blocks, cement, timber', 'Plant and tool hire', 'Subcontractor payments and CIS', 'Skip hire and waste', 'Van and fuel or mileage', 'Site insurance and PPE'],
    cis: true,
  },
  {
    slug: 'plasterers',
    name: 'Plasterer',
    plural: 'plasterers',
    emoji: '🪣',
    blurb: 'Bags, beads and boards logged in seconds. Lekhio sorts your costs and keeps you ready for the quarterly update.',
    claims: ['Plaster, beads and boards', 'Tools, trowels and mixers', 'Van costs or 55p a mile', 'Protective clothing', 'Public liability insurance', 'Materials and consumables'],
    cis: true,
  },
  {
    slug: 'roofers',
    name: 'Roofer',
    plural: 'roofers',
    emoji: '🏠',
    blurb: 'Tiles, felt and scaffolding logged from the ground. Lekhio keeps your books tidy and your tax prepared.',
    claims: ['Tiles, felt and lead', 'Scaffolding and access hire', 'Tools and safety harness', 'Van and fuel or mileage', 'CIS on subcontract work', 'Insurance and PPE'],
    cis: true,
  },
  {
    slug: 'joiners',
    name: 'Joiner',
    plural: 'joiners',
    emoji: '🪚',
    blurb: 'Timber, fixings and tools logged by text. Lekhio does the bookkeeping so you stay on the tools.',
    claims: ['Timber, sheet goods and fixings', 'Power tools and blades', 'Workshop or unit rent', 'Van costs or mileage', 'Tool insurance', 'Protective gear'],
    cis: true,
  },
  {
    slug: 'painters-and-decorators',
    name: 'Painter and decorator',
    plural: 'painters and decorators',
    emoji: '🎨',
    blurb: 'Paint, sundries and dust sheets logged in a tap. Lekhio keeps you organised and ready for tax.',
    claims: ['Paint, sundries and dust sheets', 'Brushes, rollers and tools', 'Van costs or 55p a mile', 'Overalls and protective gear', 'Public liability insurance', 'Materials and consumables'],
    cis: true,
  },
  {
    slug: 'gas-engineers',
    name: 'Gas engineer',
    plural: 'gas engineers',
    emoji: '🔥',
    blurb: 'Parts, test gear and Gas Safe, all logged from the van. Lekhio keeps your books and tax in order.',
    claims: ['Boiler parts and consumables', 'Flue gas analyser and test kit', 'Gas Safe registration', 'Van costs or mileage', 'Tools and calibration', 'Public liability insurance'],
    cis: false,
  },
  {
    slug: 'gardeners',
    name: 'Gardener',
    plural: 'gardeners',
    emoji: '🌿',
    blurb: 'Fuel, green waste and kit logged in seconds. Lekhio keeps your records straight so tax is no stress.',
    claims: ['Petrol for mowers and tools', 'Green waste removal', 'Plants, seed and compost', 'Tools and machinery', 'Van costs or 55p a mile', 'Protective gear'],
    cis: false,
  },
  {
    slug: 'cleaners',
    name: 'Cleaner',
    plural: 'cleaners',
    emoji: '🧽',
    blurb: 'Products, mileage and kit logged by text. Lekhio sorts your costs and keeps you ready for tax.',
    claims: ['Cleaning products and supplies', 'Equipment and machines', 'Mileage between jobs', 'Uniform with your logo', 'Public liability insurance', 'Phone and booking apps'],
    cis: false,
  },
  {
    slug: 'mobile-hairdressers',
    name: 'Mobile hairdresser',
    plural: 'mobile hairdressers',
    emoji: '✂️',
    blurb: 'Stock, mileage and kit logged in a tap. Lekhio keeps the books while you keep your clients happy.',
    claims: ['Colour, product and stock', 'Scissors, dryers and tools', 'Mileage to clients', 'Insurance', 'Phone and booking system', 'Training that updates your skills'],
    cis: false,
  },
  {
    slug: 'drivers',
    name: 'Self employed driver',
    plural: 'drivers',
    emoji: '🚚',
    blurb: 'Fuel, tolls and vehicle costs logged from the cab. Lekhio keeps you ready for tax with no paperwork.',
    claims: ['Fuel or simplified mileage', 'Insurance and road tax', 'Vehicle servicing and repairs', 'Parking and tolls', 'Phone and platform fees', 'Cleaning and consumables'],
    cis: false,
  },
  {
    slug: 'tilers',
    name: 'Tiler',
    plural: 'tilers',
    emoji: '🧩',
    blurb: 'Tiles, adhesive and trims logged in a tap. Lekhio sorts your costs and keeps you tax ready.',
    claims: ['Tiles, adhesive and grout', 'Trims, spacers and levellers', 'Cutters and mixing tools', 'Van costs or 55p a mile', 'Knee pads and PPE', 'Public liability insurance'],
    cis: true,
  },
  {
    slug: 'scaffolders',
    name: 'Scaffolder',
    plural: 'scaffolders',
    emoji: '🏗️',
    blurb: 'Tube, boards and transport logged from site. Lekhio keeps the books straight, CIS and all.',
    claims: ['Tube, fittings and boards', 'Harnesses and safety kit', 'Transport and haulage', 'CISRS training and cards', 'CIS on subcontract work', 'Insurance and PPE'],
    cis: true,
  },
  {
    slug: 'groundworkers',
    name: 'Groundworker',
    plural: 'groundworkers',
    emoji: '🚜',
    blurb: 'Concrete, plant hire and fuel logged by text. Lekhio keeps you ready for the quarterly update.',
    claims: ['Concrete, drainage and aggregate', 'Digger and plant hire', 'Fuel for plant and van', 'Setting out and survey kit', 'CIS on subcontract work', 'Site welfare and PPE'],
    cis: true,
  },
  {
    slug: 'landscapers',
    name: 'Landscaper',
    plural: 'landscapers',
    emoji: '🌳',
    blurb: 'Plants, paving and machinery logged in seconds. Lekhio sorts your books while you work outside.',
    claims: ['Plants, turf and paving', 'Mowers and machinery', 'Fuel and servicing', 'Tip and green waste fees', 'Van costs or 55p a mile', 'Tools and PPE'],
    cis: false,
  },
  {
    slug: 'bricklayers',
    name: 'Bricklayer',
    plural: 'bricklayers',
    emoji: '🧱',
    blurb: 'Bricks, sand and tools logged from the line. Lekhio keeps your costs and CIS in order.',
    claims: ['Bricks, blocks, sand and cement', 'Trowels, lines and tools', 'Mixer hire', 'Van costs or mileage', 'CIS on subcontract work', 'PPE and workwear'],
    cis: true,
  },
  {
    slug: 'handyman',
    name: 'Handyman',
    plural: 'handymen',
    emoji: '🛠️',
    blurb: 'Materials, mileage and odd bits logged by text. Lekhio keeps the books so you stay on the jobs.',
    claims: ['Materials and fixings', 'Tools and consumables', 'Van costs or 55p a mile', 'Phone and booking apps', 'Public liability insurance', 'Workwear and PPE'],
    cis: false,
  },
  {
    slug: 'barbers',
    name: 'Barber',
    plural: 'barbers',
    emoji: '💈',
    blurb: 'Chair rent, stock and kit logged in a tap. Lekhio keeps your books tidy while you keep the queue moving.',
    claims: ['Clippers, scissors and blades', 'Stock and consumables', 'Chair or booth rent', 'Gowns, towels and capes', 'Insurance and training', 'Phone and booking system'],
    cis: false,
  },

  // Beyond the trades. Lekhio is for every self employed person, so the claims
  // knowledge and the long tail pages cover freelancers, drivers, carers,
  // creatives and consultants too. All non CIS. Plain English allowable costs.
  {
    slug: 'freelancers',
    name: 'Freelancer',
    plural: 'freelancers',
    emoji: '💻',
    blurb: 'Log an expense by text, snap a receipt, or send a voice note. Lekhio sorts it and keeps you ready for tax, all on WhatsApp.',
    claims: ['Laptop, software and subscriptions', 'Use of home for work', 'Phone and broadband share', 'Professional insurance', 'Website and marketing', 'Training that updates your skills'],
    cis: false,
  },
  {
    slug: 'graphic-designers',
    name: 'Graphic designer',
    plural: 'graphic designers',
    emoji: '🎨',
    blurb: 'Software, kit and stock assets logged in seconds. Lekhio keeps your books so you can stay in the work.',
    claims: ['Design software subscriptions', 'Laptop, tablet and stylus', 'Fonts, stock images and assets', 'Use of home for work', 'Portfolio site and hosting', 'Phone and broadband share'],
    cis: false,
  },
  {
    slug: 'photographers',
    name: 'Photographer',
    plural: 'photographers',
    emoji: '📷',
    blurb: 'Gear, travel and studio costs logged from your phone. Lekhio keeps you tax ready between shoots.',
    claims: ['Cameras, lenses and gear', 'Editing software subscriptions', 'Studio or location hire', 'Props, backdrops and lighting', 'Travel and mileage to shoots', 'Website, insurance and backup storage'],
    cis: false,
  },
  {
    slug: 'writers',
    name: 'Writer',
    plural: 'writers and copywriters',
    emoji: '✍️',
    blurb: 'Subscriptions, research and kit logged by text. Lekhio does the bookkeeping so you can keep writing.',
    claims: ['Laptop and software', 'Research books and subscriptions', 'Use of home for work', 'Website and portfolio hosting', 'Professional memberships', 'Phone and broadband share'],
    cis: false,
  },
  {
    slug: 'web-developers',
    name: 'Web developer',
    plural: 'web developers',
    emoji: '⌨️',
    blurb: 'Hosting, software and hardware logged in a tap. Lekhio keeps your books tidy while you ship.',
    claims: ['Laptop and monitors', 'Hosting, domains and cloud', 'Software and IDE subscriptions', 'Use of home for work', 'Training and courses', 'Phone and broadband share'],
    cis: false,
  },
  {
    slug: 'personal-trainers',
    name: 'Personal trainer',
    plural: 'personal trainers',
    emoji: '🏋️',
    blurb: 'Gym hire, kit and mileage logged between clients. Lekhio keeps you ready for tax with no paperwork.',
    claims: ['Gym or studio hire', 'Equipment and weights', 'Insurance and first aid', 'Certifications and CPD', 'Mileage between clients', 'Branded kit and clothing'],
    cis: false,
  },
  {
    slug: 'beauticians',
    name: 'Beautician',
    plural: 'beauticians and nail techs',
    emoji: '💅',
    blurb: 'Stock, room rent and kit logged in seconds. Lekhio keeps the books while you keep clients glowing.',
    claims: ['Products, stock and consumables', 'Tools and equipment', 'Chair or room rent', 'Insurance and training', 'Uniform and PPE', 'Booking system and phone'],
    cis: false,
  },
  {
    slug: 'dog-walkers',
    name: 'Dog walker',
    plural: 'dog walkers and pet carers',
    emoji: '🐕',
    blurb: 'Mileage, kit and insurance logged from your phone. Lekhio keeps you tax ready between walks.',
    claims: ['Leads, harnesses and kit', 'Mileage between clients', 'Insurance and DBS checks', 'Treats and poop bags', 'Van or car running costs', 'Booking apps and phone'],
    cis: false,
  },
  {
    slug: 'childminders',
    name: 'Childminder',
    plural: 'childminders',
    emoji: '🧸',
    blurb: 'Food, toys and use of home logged by text. Lekhio applies the childminder rules and keeps you ready for tax.',
    claims: ['Food and drink for the children', 'Toys, books and craft materials', 'Use of home on the childminder scale', 'Ofsted registration and insurance', 'Training and first aid', 'Wear and tear on furniture and equipment'],
    cis: false,
  },
  {
    slug: 'tutors',
    name: 'Private tutor',
    plural: 'private tutors',
    emoji: '📚',
    blurb: 'Resources, travel and kit logged in a tap. Lekhio keeps your books so you can focus on teaching.',
    claims: ['Books, resources and subscriptions', 'Laptop and software', 'Use of home or room hire', 'DBS check and insurance', 'Website and advertising', 'Mileage to students'],
    cis: false,
  },
  {
    slug: 'driving-instructors',
    name: 'Driving instructor',
    plural: 'driving instructors',
    emoji: '🚗',
    blurb: 'Car costs, fuel and fees logged from the cab. Lekhio keeps you ready for tax with no paperwork.',
    claims: ['Dual control car lease or costs', 'Fuel or simplified mileage', 'Insurance and ADI registration', 'Servicing and repairs', 'Advertising and booking system', 'Phone and diary apps'],
    cis: false,
  },
  {
    slug: 'couriers',
    name: 'Courier',
    plural: 'couriers and delivery drivers',
    emoji: '📦',
    blurb: 'Fuel, vehicle costs and fees logged from the road. Lekhio keeps you tax ready with no admin.',
    claims: ['Fuel or simplified mileage', 'Vehicle insurance and tax', 'Servicing, tyres and repairs', 'Parking and tolls', 'Phone and platform fees', 'Bags, trolley and equipment'],
    cis: false,
  },
  {
    slug: 'taxi-drivers',
    name: 'Taxi driver',
    plural: 'taxi and private hire drivers',
    emoji: '🚕',
    blurb: 'Fuel, licence and vehicle costs logged in seconds. Lekhio keeps you ready for tax between fares.',
    claims: ['Fuel or simplified mileage', 'Licence and plate fees', 'Insurance and vehicle costs', 'Servicing and repairs', 'Radio circuit or app fees', 'Cleaning and consumables'],
    cis: false,
  },
  {
    slug: 'consultants',
    name: 'Consultant',
    plural: 'consultants',
    emoji: '📈',
    blurb: 'Travel, software and memberships logged by text. Lekhio keeps your books tidy between engagements.',
    claims: ['Laptop, phone and software', 'Use of home for work', 'Travel and mileage to clients', 'Professional indemnity insurance', 'Memberships and subscriptions', 'Training and conferences'],
    cis: false,
  },
  {
    slug: 'virtual-assistants',
    name: 'Virtual assistant',
    plural: 'virtual assistants',
    emoji: '🗂️',
    blurb: 'Software, home office and kit logged in a tap. Lekhio does the bookkeeping so you can run the day.',
    claims: ['Laptop and software subscriptions', 'Use of home for work', 'Phone and broadband share', 'Website and marketing', 'Training and courses', 'Professional insurance'],
    cis: false,
  },
  {
    slug: 'online-sellers',
    name: 'Online seller',
    plural: 'online sellers',
    emoji: '🛍️',
    blurb: 'Stock, postage and fees logged as you go. Lekhio keeps your margins and tax straight without a spreadsheet.',
    claims: ['Stock and cost of goods', 'Packaging and postage', 'Marketplace and payment fees', 'Home office or storage', 'Photography and listing tools', 'Software and subscriptions'],
    cis: false,
  },
  {
    slug: 'musicians',
    name: 'Musician',
    plural: 'musicians and DJs',
    emoji: '🎧',
    blurb: 'Gear, travel and studio time logged from your phone. Lekhio keeps you tax ready between gigs.',
    claims: ['Instruments and equipment', 'PA, lighting and cables', 'Travel and mileage to gigs', 'Rehearsal or studio hire', 'Software and subscriptions', 'Promotion and website'],
    cis: false,
  },
  {
    slug: 'therapists',
    name: 'Therapist',
    plural: 'therapists and counsellors',
    emoji: '🧘',
    blurb: 'Room hire, memberships and CPD logged in seconds. Lekhio keeps your books so you can hold space for clients.',
    claims: ['Room or clinic hire', 'Insurance and professional body fees', 'Supervision and CPD', 'Couch roll and consumables', 'Use of home share', 'Website and booking system'],
    cis: false,
  },
  {
    slug: 'makeup-artists',
    name: 'Makeup artist',
    plural: 'makeup artists',
    emoji: '💄',
    blurb: 'Kit, travel and stock logged from your phone. Lekhio keeps you tax ready between bookings.',
    claims: ['Products, stock and kit', 'Brushes and tools', 'Travel and mileage to clients', 'Insurance and training', 'Kit bag and lighting', 'Website and portfolio'],
    cis: false,
  },
  {
    slug: 'caterers',
    name: 'Caterer',
    plural: 'caterers',
    emoji: '🍽️',
    blurb: 'Ingredients, hire and mileage logged in a tap. Lekhio keeps the books while you run the kitchen.',
    claims: ['Food and ingredients', 'Packaging and disposables', 'Equipment and hire', 'Kitchen or unit rent', 'Van and mileage', 'Hygiene certification and insurance'],
    cis: false,
  },
];

export function tradeBySlug(slug: string): Trade | undefined {
  return TRADES.find((t) => t.slug === slug);
}
